### PR TITLE
Fix @main macro conflict with Julia nightly

### LINKED ISSUE #48: Current release v0.3.3 failing to build on Nightly
Hi Junfeng!

The last Wannier.jl release v0.3.3 from December 2023 is failing to precompile on Julia nightly. This currently causes the DFTK nightly tests to fail ([for example here](https://github.com/JuliaMolSim/DFTK.jl/actions/runs/10185668612/job/28175713520))

I tried to reproduce this locally in a fresh Julia nightly environment and installing Wannier gives the same error during precompilation:

<details>

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.12.0-DEV.973 (2024-08-02)
 _/ |\__'_|_|_|\__'_|  |  Commit c6732a79494 (0 days old master)
|__/                   |

(@v1.12) pkg> activate --temp
  Activating new project at `/tmp/jl_dqRu7Q`

(jl_dqRu7Q) pkg> add Wannier
   Resolving package versions...
    Updating `/tmp/jl_dqRu7Q/Project.toml`
  [2b19380a] + Wannier v0.3.3
    Updating `/tmp/jl_dqRu7Q/Manifest.toml`
  [79e6a3ab] + Adapt v4.0.4
  [4fba245c] + ArrayInterface v7.15.0
  [ada6cbde] + Bravais v0.1.9
  [23470ee3] + Brillouin v0.5.18
  [bbf7d656] + CommonSubexpressions v0.3.0
  [863f3e99] + Comonicon v1.0.8
  [34da2185] + Compat v4.15.0
  [5218b696] + Configurations v0.17.6
  [187b0558] + ConstructionBase v1.5.6
⌅ [80545937] + CrystallographyCore v0.3.3
  [9a962f9c] + DataAPI v1.16.0
  [864edb3b] + DataStructures v0.18.20
  [8bb1440f] + DelimitedFiles v1.9.1
  [163ba53b] + DiffResults v1.1.0
  [b552c78f] + DiffRules v1.15.1
  [c3f9d41a] + DirectQhull v0.2.1
  [b4f34e82] + Distances v0.10.11
  [ffbed154] + DocStringExtensions v0.9.3
  [55351af7] + ExproniconLite v0.10.11
  [8f5d6c58] + EzXML v1.2.0
  [1a297f60] + FillArrays v1.11.0
  [6a86dc24] + FiniteDiff v2.23.1
  [c58ffaec] + FortranFiles v0.6.0
  [f6369f11] + ForwardDiff v0.10.36
  [c27321d9] + Glob v1.3.1
  [92d709cd] + IrrationalConstants v0.2.2
  [692b3bcd] + JLLWrappers v1.5.0
⌅ [7031d0ef] + LazyGrids v0.4.0
  [d3d80556] + LineSearches v7.2.0
  [2ab3a3ac] + LogExpFunctions v0.3.28
  [1914dd2f] + MacroTools v0.5.13
  [e1d29d7a] + Missings v1.2.0
  [d41bc354] + NLSolversBase v7.8.3
  [77ba4419] + NaNMath v1.0.2
  [b8a86587] + NearestNeighbors v0.4.18
  [429524aa] + Optim v1.9.4
  [bac558e1] + OrderedCollections v1.6.3
  [9b87118b] + PackageCompiler v2.1.17
  [d96e819e] + Parameters v0.12.3
  [7b2266bf] + PeriodicTable v1.2.1
  [85a6dd25] + PositiveFactorizations v0.2.4
  [aea7be01] + PrecompileTools v1.2.1
  [21216c6a] + Preferences v1.4.3
  [49802e3a] + ProgressBars v1.5.1
  [189a3867] + Reexport v1.2.2
  [05181044] + RelocatableFolders v1.0.1
  [ae029012] + Requires v1.3.0
  [6c6a2e73] + Scratch v1.2.1
  [efcf1570] + Setfield v1.1.1
  [a2af1166] + SortingAlgorithms v1.2.1
  [276daf66] + SpecialFunctions v2.4.0
⌃ [f761d5c5] + Spglib v0.9.3
  [90137ffa] + StaticArrays v1.9.7
  [1e83bf80] + StaticArraysCore v1.4.3
  [10745b16] + Statistics v1.11.1
  [82ae8749] + StatsAPI v1.7.0
  [2913bbd2] + StatsBase v0.34.3
  [6ec83bb0] + StructEquality v2.1.0
  [8e1ec7a9] + SumTypes v0.5.8
  [3a884ed6] + UnPack v1.0.2
  [1986cc42] + Unitful v1.21.0
  [2b19380a] + Wannier v0.3.3
⌅ [cb1bc77f] + WannierIO v0.1.0
  [94ce4f54] + Libiconv_jll v1.17.0+0
  [efe28fd5] + OpenSpecFun_jll v0.5.5+0
⌅ [784f63db] + Qhull_jll v8.0.1003+0
  [02c8fc9c] + XML2_jll v2.13.1+0
  [ac4a9f1e] + spglib_jll v2.4.0+0
  [0dad84c5] + ArgTools v1.1.2
  [56f22d72] + Artifacts v1.11.0
  [2a0f44e3] + Base64 v1.11.0
  [ade2ca70] + Dates v1.11.0
  [8ba89e20] + Distributed v1.11.0
  [f43a241f] + Downloads v1.6.0
  [7b1f6079] + FileWatching v1.11.0
  [9fa8497b] + Future v1.11.0
  [b77e0a4c] + InteractiveUtils v1.11.0
  [dc6e5ff7] + JuliaSyntaxHighlighting v1.12.0
  [4af54fe1] + LazyArtifacts v1.11.0
  [b27032c2] + LibCURL v0.6.4
  [76f85450] + LibGit2 v1.11.0
  [8f399da3] + Libdl v1.11.0
  [37e2e46d] + LinearAlgebra v1.11.0
  [56ddb016] + Logging v1.11.0
  [d6f4376e] + Markdown v1.11.0
  [a63ad114] + Mmap v1.11.0
  [ca575930] + NetworkOptions v1.2.0
  [44cfe95a] + Pkg v1.12.0
  [de0858da] + Printf v1.11.0
  [3fa0cd96] + REPL v1.11.0
  [9a3f8284] + Random v1.11.0
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization v1.11.0
  [6462fe0b] + Sockets v1.11.0
  [2f01184e] + SparseArrays v1.12.0
  [f489334b] + StyledStrings v1.11.0
  [fa267f1f] + TOML v1.0.3
  [a4e569a6] + Tar v1.10.0
  [8dfed614] + Test v1.11.0
  [cf7118a7] + UUIDs v1.11.0
  [4ec0a83e] + Unicode v1.11.0
  [e66e0078] + CompilerSupportLibraries_jll v1.1.1+0
  [deac9b47] + LibCURL_jll v8.6.0+0
  [e37daf67] + LibGit2_jll v1.8.0+0
  [29816b5a] + LibSSH2_jll v1.11.0+1
  [c8ffd9c3] + MbedTLS_jll v2.28.6+0
  [14a3606d] + MozillaCACerts_jll v2024.3.11
  [4536629a] + OpenBLAS_jll v0.3.27+1
  [05823500] + OpenLibm_jll v0.8.1+2
  [bea87d4a] + SuiteSparse_jll v7.7.0+0
  [83775a58] + Zlib_jll v1.3.1+0
  [8e850b90] + libblastrampoline_jll v5.11.0+0
  [8e850ede] + nghttp2_jll v1.60.0+0
  [3f19e933] + p7zip_jll v17.5.0+0
        Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated -m`
Precompiling all packages...
  ✗ Wannier
  0 dependencies successfully precompiled in 7 seconds. 119 already precompiled.
  1 dependency errored.
  For a report of the errors see `julia> err`. To retry use `pkg> precompile`

julia> err
PkgPrecompileError: The following 1 direct dependency failed to precompile:

Wannier 

Failed to precompile Wannier [2b19380a-1f7e-4d7d-b1b8-8aa60b3321c9] to "/home/schmitz/.julia/compiled/v1.12/Wannier/jl_zRa5MR".
WARNING: both Comonicon and Base export "@main"; uses of it in module Wannier must be qualified
ERROR: LoadError: UndefVarError: `@main` not defined in `Wannier`
Hint: It looks like two or more modules export different bindings with this name, resulting in ambiguity. Try explicitly importing it from a particular module, or qualifying the name with the module it should come from.
Hint: a global variable of this name also exists in Base.
Stacktrace:
  [1] top-level scope
    @ :0
  [2] #macroexpand#74
    @ ./expr.jl:120 [inlined]
  [3] macroexpand
    @ ./expr.jl:118 [inlined]
  [4] docm
    @ ./docs/Docs.jl:634 [inlined]
  [5] docm(source::LineNumberNode, mod::Module, meta::Any, ex::Any)
    @ Base.Docs ./docs/Docs.jl:634
  [6] (::DocStringExtensions.var"#35#36"{typeof(DocStringExtensions.template_hook)})(::LineNumberNode, ::Vararg{Any})
    @ DocStringExtensions ~/.julia/packages/DocStringExtensions/JVu77/src/templates.jl:11
  [7] var"@doc"(::LineNumberNode, ::Module, ::String, ::Vararg{Any})
    @ Core ./boot.jl:665
  [8] include(mod::Module, _path::String)
    @ Base ./Base.jl:583
  [9] include(x::String)
    @ Wannier ~/.julia/packages/Wannier/PVW2x/src/Wannier.jl:1
 [10] top-level scope
    @ ~/.julia/packages/Wannier/PVW2x/src/Wannier.jl:12
 [11] include
    @ ./Base.jl:583 [inlined]
 [12] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2796
 [13] top-level scope
    @ stdin:4
 [14] eval
    @ ./boot.jl:438 [inlined]
 [15] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:2618
 [16] include_string
    @ ./loading.jl:2628 [inlined]
 [17] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:322
 [18] _start()
    @ Base ./client.jl:553
```

</details>

Retrying the same with the latest unrelease Wannier from `add Wannier#main` however seems to work, with all Wannier tests passing. So it seems that the next minor version bump to Wannier would fix the issue.

### PR DESCRIPTION
**Pull request by Technici4n**
Hi @qiaojunfeng! Here is a fix for #48 for the 0.3.x series. I don't know if `write_diagmat` is the correct branch, but it's the only one I could find that is based on the 0.3.3 commit.

Fixes #48.

Related: https://github.com/comonicon/Comonicon.jl/issues/257.

### CODE REVIEW

**Comment by Technici4n** [comment]
Hey thanks for the quick response.

I have fixed the Aqua test by removing the `DelimitedFiles` dependency. As far as I can tell it is only used through `WannierIO` now.

To fix the other tests, I also had to disable the `wannierize/coopt.jl` tests. They rely on `iron` fixtures that I could not find anywhere in the repo or Git history.

**Comment by Technici4n** [comment]
The tests are fine now, but the documentation is failing to build. 😓
There is no `docs` folder on this branch, so I would say that can be safely ignored?

**Comment by qiaojunfeng** [comment]
Thanks Bruno! I guess you want a new release `v0.3.4` for DFTK tests?

**Comment by Technici4n** [comment]
Thank you! Yes please. :smile:

**Comment by qiaojunfeng** [comment]
> Thank you! Yes please. 😄

OK done
https://github.com/qiaojunfeng/Wannier.jl/releases/tag/v0.3.4

**Comment by Technici4n** [comment]
CI now passes on DFTK, thanks a lot once again!

**Pull request merged**
